sudo: required
services:
  - docker

before_install:
  - docker build -t vjdevopsengineer/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true vjdevopsengineer/react-test npm test

after_success:
  - docker build -t vjdevopsengineer/mc-client ./client
  - docker build -t vjdevopsengineer/mc-nginx ./nginx
  - docker build -t vjdevopsengineer/mc-server ./server
  - docker build -t vjdevopsengineer/mc-worker ./worker
  - echo "$DOCKER_PASSWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vjdevopsengineer/mc-client
  - docker push vjdevopsengineer/mc-nginx
  - docker push vjdevopsengineer/mc-server
  - docker push vjdevopsengineer/mc-worker
# deploy:
#   provider: elasticbeanstalk
#   region: 'ap-south-1'
#   app: 'multi-docker'
#   env: 'Multi-docker-env'
#   bucket_name: 'elasticbeanstalk-ap-south-1-144979326168'
#   bucket_path: 'multi-docker'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY